using Pds.FundingClaim.CorporateSchema.FundingClaims;

namespace Pds.FundingClaim.Repositories.DataModels
{
    /// <summary>
    /// Contains Original Data for the <see cref="DataModels.FundingClaim"/>.
    /// </summary>
    public partial class FundingClaimData
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="FundingClaimData"/> class.
        /// Private Default Constructor.
        /// </summary>
        public FundingClaimData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FundingClaimData"/> class.
        /// Full Constructor.
        /// </summary>
        /// <param name="originalFundingClaim">The original Funding Claim that contains the data.</param>
        public FundingClaimData(CorporateSchema.FundingClaims.FundingClaim originalFundingClaim)
        {
            OriginalFundingClaimJson = originalFundingClaim.ToJson();
        }

        #endregion


        #region Properties

        /// <summary>
        /// Gets or sets identifier for the funding claim data.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the owning <see cref="DataModels.FundingClaim"/>. In spite of the plural-sounding autogenerated
        /// model name, FundingClaims refers to a single funding claim object.
        /// </summary>
        public virtual FundingClaim FundingClaim { get; set; }

        /// <summary>
        /// Gets or sets the original Funding Claim that contains the data.
        /// </summary>
        public string OriginalFundingClaimXml { get; set; }

        /// <summary>
        /// Gets or sets the original Funding Claim as json in the repository.
        /// </summary>
        public string OriginalFundingClaimJson { get; set; }

        #endregion
    }
}